version: 0.2.0.{build}
image:
  - Visual Studio 2017
cache:
- C:\ProgramData\chocolatey\bin -> scripts\ps\appveyor_install.ps1
- C:\ProgramData\chocolatey\lib -> scripts\ps\appveyor_install.ps1
- secure-file -> scripts\ps\appveyor_install.ps1
environment:
  OPENRCT2_ORG_TOKEN:
    secure: leQX3xCQpmBLGuMqrxjFlzexDt96ypNRMM5TTRVHbGE8PwVg9crgeykLc2BIZU6HDHveJCHqh2cGMdHtHYJYcw==
  BUILD_SERVER: AppVeyor
  PATH: C:\ProgramData\chocolatey\bin;$(PATH);C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
install:
- mkdir C:\projects\deps
- cd C:\projects\deps

# Install Ninja
- set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
- appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
- 7z x ninja.zip -oC:\projects\deps\ninja > nul
- set PATH=C:\projects\deps\ninja;%PATH%
- ninja --version

- mkdir C:\projects\openrct2\build
- cd C:\projects\openrct2\build
# Download deps
- set DEPS_URL="https://ci.appveyor.com/api/buildjobs/90txeybww63xi8r3/artifacts/vcpkg/vcpkg-export-20180512-015154.zip"
- appveyor DownloadFile %DEPS_URL% -FileName deps.zip
- 7z x deps.zip -oC:\projects\openrct2\build

# Source the build environment
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

- set PATH="C:\Program Files\LLVM\bin";%PATH%
- clang-cl -v

- cmake -G Ninja .. -DCMAKE_TOOLCHAIN_FILE=vcpkg-export-20180512-015154/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-winssl -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_TESTS=on -DCMAKE_CXX_COMPILER=clang-cl
- ninja -k0
- ctest --output-on-failure
- ps: >-
    .\scripts\ps\appveyor_install.ps1
platform:
  - x64
configuration: Release
build:
  parallel: true
  project: openrct2.proj
test_script:
- ps: msbuild openrct2.proj /t:Test /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\artifacts\test-results.xml))
artifacts:
- path: .\artifacts\openrct2-portable*.zip
  name: OpenRCT2-portable
- path: .\artifacts\openrct2-installer*.exe
  name: OpenRCT2-installer
- path: .\artifacts\openrct2-symbols*.zip
  name: OpenRCT2 debug symbols
deploy_script:
- ps: >-
    .\scripts\ps\appveyor_deploy.ps1
