#!/usr/bin/env bash

set -e

# Ensure we are in root directory
if [[ $(uname) == "Darwin" ]]; then
    basedir="$(perl -MCwd=abs_path -le 'print abs_path readlink(shift);' `dirname $0`/..)"
else
    basedir="$(readlink -f `dirname $0`/..)"
fi
cd $basedir

if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
    # Patch version.h
    echo -e "\033[0;36mPatching version.h...\033[0m"
    fileversion=$OPENRCT2_VERSION.$OPENRCT2_BUILD
    productversion="$fileversion-${OPENRCT2_SHA1_SHORT}"
    fileversion=${fileversion//./,}
    # FILEVERSION in the resource file can only take up to 4 digits in the version string, so we remove the surplus of version numbers
    fileversion=$(echo $fileversion | cut -f1-4 -d",")
    echo "#define OPENRCT2_FILE_VERSION $fileversion" > "resources/version.h"
    echo "#define OPENRCT2_PRODUCT_VERSION \"$productversion\"" >> "resources/version.h"
    cat "resources/version.h"

    # # Build everything
    # echo -e "\033[0;36mBuilding OpenRCT2 for Windows $CONFIGURATION|$PLATFORM...\033[0m"

    # # Add PreferredToolArchitecture if OPENRCT2_HOST_ARCH_DISPLAY is set
    # MSBUILD_PROPS="-p:Breakpad=true -p:UsePCH=true"
    # if [[ -n "$OPENRCT2_HOST_ARCH_DISPLAY" ]]; then
    #     MSBUILD_PROPS="$MSBUILD_PROPS -p:PreferredToolArchitecture=${PreferredToolArchitecture}"
    #     echo "Using MSBuild property: PreferredToolArchitecture=${PreferredToolArchitecture}"
    # fi

    # # Check if msbuild is already in PATH (e.g., from setup-msbuild action)
    # if command -v msbuild &> /dev/null; then
    #     echo "Using msbuild from PATH (setup-msbuild action)"
    #     msbuild openrct2.proj -t:build $MSBUILD_PROPS
    # else
    #     echo "Using vstool wrapper to setup VS environment"
    #     vstool msbuild openrct2.proj -t:build $MSBUILD_PROPS
    # fi

    # # Create openrct2.exe and openrct2.com with correct subsystem
    # cp bin/openrct2.exe bin/openrct2.com

    # # Check if editbin is already in PATH
    # if command -v editbin &> /dev/null; then
    #     editbin //subsystem:console bin/openrct2.com
    #     editbin //subsystem:windows bin/openrct2.exe
    # else
    #     vstool editbin //subsystem:console bin/openrct2.com
    #     vstool editbin //subsystem:windows bin/openrct2.exe
    # fi
else
    echo -e "\033[0;36mBuilding OpenRCT2...\033[0m"
    mkdir -p bin && cd bin
    export DESTDIR=install
    cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=/usr "$@"

    ninja -k0 all install
fi
