name: openrct2-test-janisozaur
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
icon: resources/logo/icon_noflag.svg
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  openrct2:
    command: bin/wrapper openrct2 --openrct-data-path=$SNAP/share/openrct2/
    desktop: share/applications/openrct2.desktop
    plugs: [x11, home, network, network-bind, opengl, unity7, pulseaudio]

  glxinfo:
    command: env LIBGL_DRIVERS_PATH=$SNAP/usr/lib/x86_64-linux-gnu/dri LIBGL_DEBUG=verbose glxinfo
    plugs: [x11, home, network, network-bind, opengl, unity7, pulseaudio]

  glxinfo2:
    command: bin/wrapper glxinfo
    plugs: [x11, home, network, network-bind, opengl, unity7, pulseaudio]

  env:
    command: bin/wrapper env
    plugs: [x11, home, network, network-bind, opengl, unity7, pulseaudio]

parts:
  openrct2:
    source: .
    plugin: cmake
    configflags: [ "-DCMAKE_BUILD_TYPE=debug" ]
    build-packages:
            - g++
            - make
            - libsdl2-dev
            - libzip-dev
            - libpng-dev
            - libspeexdsp-dev
            - libssl-dev
            - libcurl4-openssl-dev
            - zlib1g-dev
            - libfreetype6-dev
            - libfontconfig1-dev
            - libjansson-dev
            - pkg-config
    stage-packages:
            - libc6
            - libstdc++6
            - libgl1-mesa-dri
            - mesa-utils

  wrapper:
    plugin: dump
    organize:
      distribution/linux/snap-wrapper.sh: bin/wrapper
