name: CI
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.github/*_TEMPLATE/**'
      - '.github/workflows/localisation.yml'
      - '.gitignore'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.github/*_TEMPLATE/**'
      - '.github/workflows/localisation.yml'
      - '.gitignore'
      - '.vscode/**'
defaults:
  run:
    shell: bash
env:
  OPENRCT2_BUILD_SERVER: GitHub
  OPENRCT2_ORG_TOKEN: ${{ secrets.OPENRCT2_ORG_TOKEN }}
  BACKTRACE_IO_TOKEN: ${{ secrets.BACKTRACE_IO_TOKEN }}
  OPENRCT2_VERSION: 0.4.15

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows-simplysign:
    name: Windows SimplySign
    runs-on: windows-latest
    steps:
      - name: Download SimplySign
        run: |
          mkdir -p C:/OpenRCT2/SimplySign
          curl -L -o C:/OpenRCT2/SimplySign/SimplySign.exe https://files.certum.eu/software/SimplySignDesktop/Windows/9.1.11.61/SimplySignDesktop-9.1.11.61-64-bit-en.msi
          msiexec /i C:/OpenRCT2/SimplySign/SimplySign.exe /qn /norestart
