name: CI
on: [push, pull_request]
jobs:
  windows-cmake-msvc-arm:
    name: Windows MSVC CMake ARM64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v2
        id: runvcpkg
        with:
          vcpkgGitCommitId: 2f7a104d4d6f1f3790db929f85a4086aa6973d7f
          vcpkgTriplet: 'arm64-windows'
          vcpkgArguments: 'duktape curl libzip freetype jansson libpng openssl sdl2 speexdsp zlib'
      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}\\installed\\arm64-windows
      - name: 'Build with CMake'
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          buildDirectory: '${{ runner.workspace }}/build'
          cmakeAppendedArgs: '-DDISABLE_DISCORD_RPC=on -DDISABLE_OPENGL=on -A ARM64'
          vcpkgTriplet: arm64-windows
          cmakeBuildType: Release
          cmakeGenerator: VS16Arm64
          buildWithCMakeArgs: '--config Release -j 2'
      - name: Upload exe
        uses: actions/upload-artifact@v2
        with:
          name: openrct2-arm64
          path: '${{ runner.workspace }}/build/Release/openrct2.exe'
      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: openrct2-arm64
          path: ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}\\installed\\arm64-windows\\bin\\*.dll
